import {
  AddCircleIcon,
  AddIcon,
  Album01Icon,
  AlertCircleIcon,
  Analytics01Icon,
  Archive01Icon,
  ArrowDataTransferVerticalIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Bicycle01Icon,
  BluetoothIcon,
  Calculator01Icon,
  Camera01Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CashierIcon,
  CheckmarkCircle01Icon,
  ChefHatIcon,
  CircleIcon,
  Clock01Icon,
  CloudDownloadIcon,
  CloudOffIcon,
  ComputerIcon,
  CreditCardIcon,
  Delete02Icon,
  DiningTableIcon,
  Dish01Icon,
  Download01Icon,
  Edit02Icon,
  EllipseIcon,
  ExternalLinkIcon,
  FavouriteIcon,
  Fire03Icon,
  FunnelIcon,
  GridViewIcon,
  Home01Icon,
  HandPlatterIcon,
  Image01Icon,
  InformationCircleIcon,
  LanguageCircleIcon,
  LayerIcon,
  Link01Icon,
  ListViewIcon,
  Location01Icon,
  LockPasswordIcon,
  Logout01Icon,
  Mail01Icon,
  MapsIcon,
  Menu01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoreHorizontalCircle01Icon,
  Notification03Icon,
  PackageIcon,
  PlayIcon,
  PrinterIcon,
  QrCodeIcon,
  RadioButtonIcon,
  ReceiptIcon,
  RefreshIcon,
  Restaurant01Icon,
  SaveIcon,
  Search01Icon,
  Share01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  Settings01Icon,
  StarIcon,
  Store01Icon,
  Sun01Icon,
  TableRoundIcon,
  Tag01Icon,
  TagsIcon,
  Tick01Icon,
  TriangleAlertIcon,
  UserCircleIcon,
  UserIcon,
  UserMultiple02Icon,
  ViewIcon,
  ViewOffSlashIcon,
  Wallet01Icon,
  Queue01Icon,
} from "@hugeicons/core-free-icons";

export const AppIcons = {
  add: AddIcon,
  addCircle: AddCircleIcon,
  albums: Album01Icon,
  alertCircle: AlertCircleIcon,
  analytics: Analytics01Icon,
  archive: Archive01Icon,
  arrowBack: ArrowLeft01Icon,
  arrowDown: ArrowDown01Icon,
  arrowForward: ArrowRight01Icon,
  arrowUp: ArrowUp01Icon,
  bag: ShoppingBag01Icon,
  bicycle: Bicycle01Icon,
  bluetooth: BluetoothIcon,
  calculator: Calculator01Icon,
  camera: Camera01Icon,
  card: CreditCardIcon,
  cart: ShoppingCart01Icon,
  checkmark: Tick01Icon,
  checkmarkCircle: CheckmarkCircle01Icon,
  chefHat: ChefHatIcon,
  chevronBack: ArrowLeft01Icon,
  chevronDown: ArrowDown01Icon,
  chevronForward: ArrowRight01Icon,
  chevronUp: ArrowUp01Icon,
  close: Cancel01Icon,
  closeCircle: CancelCircleIcon,
  cashier: CashierIcon,
  cloudDownload: CloudDownloadIcon,
  cloudOffline: CloudOffIcon,
  cube: PackageIcon,
  desktop: ComputerIcon,
  diningTable: DiningTableIcon,
  download: Download01Icon,
  ellipse: EllipseIcon,
  eye: ViewIcon,
  eyeOff: ViewOffSlashIcon,
  flame: Fire03Icon,
  funnel: FunnelIcon,
  food: Dish01Icon,
  grid: GridViewIcon,
  heart: FavouriteIcon,
  home: Home01Icon,
  handPlatter: HandPlatterIcon,
  image: Image01Icon,
  informationCircle: InformationCircleIcon,
  language: LanguageCircleIcon,
  layers: LayerIcon,
  link: Link01Icon,
  list: ListViewIcon,
  location: Location01Icon,
  lockClosed: LockPasswordIcon,
  logout: Logout01Icon,
  mail: Mail01Icon,
  map: MapsIcon,
  menu: Menu01Icon,
  moon: Moon02Icon,
  notifications: Notification03Icon,
  open: ExternalLinkIcon,
  options: MoreHorizontalCircle01Icon,
  pencil: Edit02Icon,
  people: UserMultiple02Icon,
  person: UserIcon,
  personCircle: UserCircleIcon,
  play: PlayIcon,
  priceTag: Tag01Icon,
  priceTags: TagsIcon,
  print: PrinterIcon,
  qrCode: QrCodeIcon,
  radioOff: CircleIcon,
  radioOn: RadioButtonIcon,
  receipt: ReceiptIcon,
  remove: MinusSignIcon,
  restaurant: Restaurant01Icon,
  refresh: RefreshIcon,
  save: SaveIcon,
  search: Search01Icon,
  settings: Settings01Icon,
  share: Share01Icon,
  star: StarIcon,
  storefront: Store01Icon,
  sunny: Sun01Icon,
  swapVertical: ArrowDataTransferVerticalIcon,
  tableRound: TableRoundIcon,
  time: Clock01Icon,
  trash: Delete02Icon,
  wallet: Wallet01Icon,
  warning: TriangleAlertIcon,
  queue: Queue01Icon,
} as const;
